name: data-scraper

services: 
  api:
    build: 
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - data-scraper
    ports:
      - 8080:8080

  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    # env_file: ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - data-scraper
    ports:
      - 5173:5173
    depends_on:
      - api

networks:
  data-scraper:
    driver: bridge
